Seed: null
 # POI locations must be formatted as [{'loc': [#,#], 'value': #}, {'loc': [#,#], 'value': #}, ...]
Initial POI Locations: null
 # Agent positions must be formatted as [{'loc': [#,#], 'theta': #}, {'loc': [#,#], 'theta': #}, ...]
Initial Agent Positions: null
Number of Agents: 5
Number of POIs: 4
World Width: 50
World Length: 50
Coupling: 1
Observation Radius: 3.0
Consideration Radius: 10.0
Minimum Distance: 1.0
Steps: 100
Epochs: 10
